### ISSUE TITLE
missing results folder creates error

### ISSUE THREAD

**Issue by zoltuz** [afvillaverde/strike-goldd_2.1#1]
Hi Alex, 
The unedited options.m wants to save the results in a 'results' folder, which doesn't exist by default. (Creating one manually solves the problem) 

Adding the results folder permanently or creating one at installation would be a good solution.
e.g.  
mkdir('results')
addpath(fullfile(strikegoldd_path,'results'))

**Comment by afvillaverde** [comment]
Hi Zoltan, and sorry for my late reply! I have changed it so that now it creates a results folder at installation, if it does not exist. Thaks for spotting this issue!
